// Shared constants for Event Builder
export const ENTITY_TYPE_OPTIONS = ['All', 'Branch', 'Subsi', 'Assoc', 'Tmu'];

export const BUSINESS_EVENT_OPTIONS = ['Inception', 'Utilization', 'Rollover', 'Termination'];
export const HEDGE_METHOD_OPTIONS = ['MTM', 'COH'];
export const CURRENCY_TYPE_OPTIONS = ['Restricted', 'Non-Restricted'];
export const HEDGING_INSTRUMENT_OPTIONS = ['FX Swap', 'FX NDF', 'IRD Xccy Swap'];
export const NAV_TYPE_OPTIONS = ['COI', 'RE+reserves'];

export const GL_BE_CODE_OPTIONS = [
  'SG_HAWK_DR_UHDCOILOCKBACKFXGAIN_TMU',
  'SG_HAWK_CR_UHDCOILOCKBACKFXLOSS_TMU',
  'SG_HAWK_DR_UHDCOILOCKBACKFXGAIN_BR',
  'SG_HAWK_CR_UHDCOILOCKBACKFXLOSS_BR',
  'SG_HAWK_DR_UHCOILOCKBACKFXGAIN_TMU',
  'SG_HAWK_CR_UHCOILOCKBACKFXLOSS_TMU',
  'SG_HAWK_DR_COILOCKBACKFXGAIN_REL',
  'SG_HAWK_CR_COILOCKBACKFXLOSS_REL',
  'SG_HAWK_DR_FWDCOILOCKBACKFXGAIN_TMU',
  'SG_HAWK_CR_FWDCOILOCKBACKFXLOSS_TMU',
  'SG_HAWK_DR_COILOCKBACKFXGAIN_BR',
  'SG_HAWK_CR_COILOCKBACKFXLOSS_BR',
  'SG_HAWK_DR_HGGICFXGAIN_TMU',
  'SG_HAWK_CR_HGGICFXLOSS_TMU',
  'SG_HAWK_DR_SWAPCOILOCKBACKFXGAIN_BR',
  'SG_HAWK_CR_SWAPCOILOCKBACKFXLOSS_BR',
  'SG_HAWK_DR_FWDCOILOCKBACKFXGAIN_BR',
  'SG_HAWK_CR_FWDCOILOCKBACKFXLOSS_BR',
  'SG_HAWK_DR_OPENHGGICFXGAIN_TMU',
  'SG_HAWK_CR_OPENHGGICFXLOSS_TMU',
];
